Repository PeterHHartmann/SPAC-10-11-GroceryDelivery, pull requests merged in 2025-04, with the labels that each got.

#6 Initial data model design ERD complete
  docs/ERD.plantuml
Labels: documentation

#14 sketches of store, cart and product detail pages
  docs/frontend-ui.excalidraw
Labels: documentation

#15 added docker compose file with postgres service
  docker-compose.yml
Labels: enhancement

#17 Establish new Grocery Delivery API project structure
  .gitignore
  GroceryDeliveryAPI.sln
  GroceryDeliveryAPI/Controllers/WeatherForecastController.cs
  GroceryDeliveryAPI/GroceryDeliveryAPI.csproj
  GroceryDeliveryAPI/GroceryDeliveryAPI.csproj.user
  GroceryDeliveryAPI/GroceryDeliveryAPI.http
  GroceryDeliveryAPI/Program.cs
  GroceryDeliveryAPI/Properties/launchSettings.json
  GroceryDeliveryAPI/WeatherForecast.cs
  GroceryDeliveryAPI/appsettings.Development.json
  GroceryDeliveryAPI/appsettings.json
Labels: project structure

#18 generated initial frontend app with Vite
  .gitignore
  GroceryDeliveryClient/.cta.json
  GroceryDeliveryClient/.vscode/settings.json
  GroceryDeliveryClient/README.md
  GroceryDeliveryClient/biome.json
  GroceryDeliveryClient/components.json
  GroceryDeliveryClient/index.html
  GroceryDeliveryClient/package-lock.json
  GroceryDeliveryClient/package.json
  GroceryDeliveryClient/public/favicon.ico
  GroceryDeliveryClient/public/logo192.png
  GroceryDeliveryClient/public/logo512.png
  GroceryDeliveryClient/public/manifest.json
  GroceryDeliveryClient/public/robots.txt
  GroceryDeliveryClient/src/components/Header.tsx
  GroceryDeliveryClient/src/components/demo.FormComponents.tsx
  GroceryDeliveryClient/src/components/ui/button.tsx
  GroceryDeliveryClient/src/components/ui/input.tsx
  GroceryDeliveryClient/src/components/ui/label.tsx
  GroceryDeliveryClient/src/components/ui/select.tsx
  GroceryDeliveryClient/src/components/ui/slider.tsx
  GroceryDeliveryClient/src/components/ui/switch.tsx
  GroceryDeliveryClient/src/components/ui/textarea.tsx
  GroceryDeliveryClient/src/data/demo-table-data.ts
  GroceryDeliveryClient/src/hooks/demo.form-context.ts
  GroceryDeliveryClient/src/hooks/demo.form.ts
  GroceryDeliveryClient/src/integrations/tanstack-query/layout.tsx
  GroceryDeliveryClient/src/integrations/tanstack-query/root-provider.tsx
  GroceryDeliveryClient/src/lib/utils.ts
  GroceryDeliveryClient/src/logo.svg
  GroceryDeliveryClient/src/main.tsx
  GroceryDeliveryClient/src/reportWebVitals.ts
  GroceryDeliveryClient/src/routeTree.gen.ts
  GroceryDeliveryClient/src/routes/__root.tsx
  GroceryDeliveryClient/src/routes/demo.form.address.tsx
  GroceryDeliveryClient/src/routes/demo.form.simple.tsx
  GroceryDeliveryClient/src/routes/demo.table.tsx
  GroceryDeliveryClient/src/routes/demo.tanstack-query.tsx
  GroceryDeliveryClient/src/routes/index.tsx
  GroceryDeliveryClient/src/styles.css
  GroceryDeliveryClient/tsconfig.json
  GroceryDeliveryClient/vite.config.js
Labels: project structure

#21 20 client layout implementation
  GroceryDeliveryClient/.cta.json
  GroceryDeliveryClient/.vscode/settings.json
  GroceryDeliveryClient/README.md
  GroceryDeliveryClient/biome.json
  GroceryDeliveryClient/components.json
  GroceryDeliveryClient/eslint.config.js
  GroceryDeliveryClient/index.html
  GroceryDeliveryClient/package-lock.json
  GroceryDeliveryClient/package.json
  GroceryDeliveryClient/public/manifest.json
  GroceryDeliveryClient/public/robots.txt
  GroceryDeliveryClient/public/vite.svg
  GroceryDeliveryClient/src/App.tsx
  GroceryDeliveryClient/src/api/queryClient.ts
  GroceryDeliveryClient/src/assets/placeholder-image.svg
  GroceryDeliveryClient/src/assets/react.svg
  GroceryDeliveryClient/src/components/Header.tsx
  GroceryDeliveryClient/src/components/demo.FormComponents.tsx
  GroceryDeliveryClient/src/components/ui/button.tsx
  GroceryDeliveryClient/src/components/ui/input.tsx
  GroceryDeliveryClient/src/components/ui/label.tsx
  GroceryDeliveryClient/src/components/ui/navigation-menu.tsx
  GroceryDeliveryClient/src/components/ui/select.tsx
  GroceryDeliveryClient/src/components/ui/separator.tsx
  GroceryDeliveryClient/src/components/ui/slider.tsx
  GroceryDeliveryClient/src/components/ui/switch.tsx
  GroceryDeliveryClient/src/components/ui/textarea.tsx
  GroceryDeliveryClient/src/data/demo-table-data.ts
  GroceryDeliveryClient/src/hooks/demo.form-context.ts
  GroceryDeliveryClient/src/hooks/demo.form.ts
  GroceryDeliveryClient/src/index.css
  GroceryDeliveryClient/src/integrations/tanstack-query/layout.tsx
  GroceryDeliveryClient/src/integrations/tanstack-query/root-provider.tsx
  GroceryDeliveryClient/src/layout/app-navigation.tsx
  GroceryDeliveryClient/src/layout/root-layout.tsx
  GroceryDeliveryClient/src/lib/utils.ts
  GroceryDeliveryClient/src/logo.svg
  GroceryDeliveryClient/src/main.tsx
  GroceryDeliveryClient/src/pages/index/index-page.tsx
  GroceryDeliveryClient/src/reportWebVitals.ts
  GroceryDeliveryClient/src/routeTree.gen.ts
  GroceryDeliveryClient/src/router/router.tsx
  GroceryDeliveryClient/src/routes/__root.tsx
  GroceryDeliveryClient/src/routes/demo.form.address.tsx
  GroceryDeliveryClient/src/routes/demo.form.simple.tsx
  GroceryDeliveryClient/src/routes/demo.table.tsx
  GroceryDeliveryClient/src/routes/demo.tanstack-query.tsx
  GroceryDeliveryClient/src/routes/index.tsx
  GroceryDeliveryClient/src/styles.css
  GroceryDeliveryClient/src/vite-env.d.ts
  GroceryDeliveryClient/tsconfig.app.json
  GroceryDeliveryClient/tsconfig.json
  GroceryDeliveryClient/tsconfig.node.json
  GroceryDeliveryClient/vite.config.js
  GroceryDeliveryClient/vite.config.ts
Labels: enhancement
